### PR TITLE
Bill/feature/faq section

### PR DESCRIPTION
**Pull request by Adneths**

### CODE REVIEW

**Review by kyle1373 — CHANGES_REQUESTED** [review]
Some notes (refer to https://www.figma.com/file/NY2yXR5zDqGdFrO1xeUGw5/hard-hack-website?node-id=627%3A80 for figma)

- The house in the background should by roughly at the same level as geisel library. This makes it so the FAQ text is still readable on the blue background when the user scrolls down.

- Make the “FAQ” text smaller as shown on the figma. Right now it seems too big and stands out a little too much.

- Arrows should be initially pointing down, not to the right before dropdown is clicked on each FAQ section. Then when the user clicks on the arrows, they point up.

- Have a FAQ button on the top right of the page which scrolls to the FAQ section through an ease transition (not immediately).

- Make the faq dropdowns have a max width from the left and the right as shown on the figma. Right now, the lines extend across the screen, whereas they should have some space on the left and the right. My advice is to have a max width, where if the width exceeds a certain amount, it should just stay at that width. This width should match the figma on the “Desktop” frames.

**Comment by Adneths** [comment]
> Some notes (refer to https://www.figma.com/file/NY2yXR5zDqGdFrO1xeUGw5/hard-hack-website?node-id=627%3A80 for figma)
> 
> * The house in the background should by roughly at the same level as geisel library. This makes it so the FAQ text is still readable on the blue background when the user scrolls down.
> * Make the “FAQ” text smaller as shown on the figma. Right now it seems too big and stands out a little too much.
> * Arrows should be initially pointing down, not to the right before dropdown is clicked on each FAQ section. Then when the user clicks on the arrows, they point up.
> * Have a FAQ button on the top right of the page which scrolls to the FAQ section through an ease transition (not immediately).
> * Make the faq dropdowns have a max width from the left and the right as shown on the figma. Right now, the lines extend across the screen, whereas they should have some space on the left and the right. My advice is to have a max width, where if the width exceeds a certain amount, it should just stay at that width. This width should match the figma on the “Desktop” frames.

Since FAQ is below About, I think any tweaks to the background should be made on the unified version of the page. And same goes for adding a menu bar since that is shared with the About section and other sections. Unless you just want me to make the menu bar.

Also I'm not sure what you mean with the last point because the dropdowns don't extend across the whole screen.
image

**Comment by kyle1373** [comment]
> Since FAQ is below About, I think any tweaks to the background should be made on the unified version of the page. And same goes for adding a menu bar since that is shared with the About section and other sections. Unless you just want me to make the menu bar.

While yes FAQ is below about, those sections in HTML should not be position specific. They should just be stacked below one another when new sections are added. With Michele's changes, the background should not scale with the window size, but rather it should just stay level with the title.

image

This is what it looks like now.

image
image

Currently, the house goes lower and lower depending on the height of the window, which is not what Michele is asking. I do agree that perhaps we should make a separate branch for this change. However, since it is a minor addition that does affect how the page looks and feels when the users go to the FAQ section, we might as well modify the background before deploying it. As for the menu bar, we can delegate it to a separate task instead.

> Also I'm not sure what you mean with the last point because the dropdowns don't extend across the whole screen. image

I originally tested this with a vertical desktop screen, and the lines seemed to stretch across the screen. Perhaps the width was too wide in this case, which is why it made it seem like it was stretching across the screen when it wasn't. Looks good after looking at it again.

Also it seems like the arrow rotation still points to the right when not expanded and down when it is expanded in the FAQ section. They should be initially pointing down when not expanded and the up when expanded. I pulled from the branch already and the change doesn't seem to be there.

image

**Review by kyle1373 — APPROVED** [review]
LGTM

**Pull request merged**
